spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.project-id=${GOOGLE_PROJECT_ID}

spring.ai.google.genai.embedding.options.model=text-embedding-004
spring.ai.google.genai.chat.options.model=gemini-2.5-flash