spring.application.name=AlienNeutrilizer
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/AlienBase
spring.datasource.username=postgres
spring.datasource.password=dgblood

jwt.secret=youCannotAccessHeshansUSOIAppAREA51SecretKey2026
jwt.expiration=86400000

# Google Gemini API
spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.project-id=${GOOGLE_PROJECT_ID}
spring.ai.google.genai.location=us-central1

# Chat model
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.7

# Embedding model
spring.ai.google.genai.embedding.text.model=text-embedding-004
spring.ai.google.genai.embedding.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.embedding.project-id=${GOOGLE_PROJECT_ID}
spring.ai.google.genai.embedding.location=us-central1

spring.ai.vectorstore.pgvector.initialize-schema=true

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
server.error.include-binding-errors=always


